-- profiles table
CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at TIMESTAMPTZ,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  website TEXT,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Function to create a profile for a new user
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to call the function on new user creation
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- daily_pages table
CREATE TABLE public.daily_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  page_date DATE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (user_id, page_date)
);

ALTER TABLE public.daily_pages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own daily pages." ON public.daily_pages
  FOR ALL USING (auth.uid() = user_id);

-- todos table
CREATE TABLE public.todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_page_id BIGINT NOT NULL REFERENCES public.daily_pages(id) ON DELETE CASCADE,
  task TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '대기', -- 대기, 진행, 완료
  importance INT DEFAULT 1, -- 1: 낮음, 2: 보통, 3: 높음
  memo TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own todos." ON public.todos
  FOR ALL USING (auth.uid() = (
    SELECT user_id FROM public.daily_pages WHERE id = daily_page_id
  ));

-- incomes table
CREATE TABLE public.incomes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_page_id BIGINT NOT NULL REFERENCES public.daily_pages(id) ON DELETE CASCADE,
  amount NUMERIC(15, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL, -- KRW, USD
  income_type TEXT, -- 급여, 부수입, 투자수익
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own incomes." ON public.incomes
  FOR ALL USING (auth.uid() = (
    SELECT user_id FROM public.daily_pages WHERE id = daily_page_id
  ));

-- expenses table
CREATE TABLE public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_page_id BIGINT NOT NULL REFERENCES public.daily_pages(id) ON DELETE CASCADE,
  amount NUMERIC(15, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL, -- KRW, USD
  category TEXT, -- 식비, 교통, 구독
  is_fixed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own expenses." ON public.expenses
  FOR ALL USING (auth.uid() = (
    SELECT user_id FROM public.daily_pages WHERE id = daily_page_id
  ));

-- exchange_rates table
CREATE TABLE public.exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rate_date DATE NOT NULL,
  from_currency VARCHAR(3) NOT NULL,
  to_currency VARCHAR(3) NOT NULL,
  rate NUMERIC(15, 6) NOT NULL,
  UNIQUE(rate_date, from_currency, to_currency)
);

-- This table is public and doesn't need RLS for reads.
-- For writes, you might want to restrict it to a service role key.
ALTER TABLE public.exchange_rates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Exchange rates are viewable by everyone." ON public.exchange_rates FOR SELECT USING (true);
-- Add a policy for inserts/updates if you plan to update rates via the API.
-- For example, allowing only a service_role to insert. It's safer to do this from a backend function.

-- stock_trades table
CREATE TABLE public.stock_trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_page_id BIGINT NOT NULL REFERENCES public.daily_pages(id) ON DELETE CASCADE,
  ticker TEXT NOT NULL,
  market TEXT NOT NULL, -- KRX, NYSE, NASDAQ
  trade_type TEXT NOT NULL, -- 매수, 매도
  quantity INT NOT NULL,
  price NUMERIC(15, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.stock_trades ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own stock trades." ON public.stock_trades
  FOR ALL USING (auth.uid() = (
    SELECT user_id FROM public.daily_pages WHERE id = daily_page_id
  ));

-- investment_memos table
CREATE TABLE public.investment_memos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trade_id BIGINT NOT NULL REFERENCES public.stock_trades(id) ON DELETE CASCADE,
  memo TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.investment_memos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own investment memos." ON public.investment_memos
  FOR ALL USING (auth.uid() = (
    SELECT user_id FROM public.daily_pages
    JOIN public.stock_trades ON public.daily_pages.id = public.stock_trades.daily_page_id
    WHERE public.stock_trades.id = trade_id
  ));
